### ISSUE TITLE
JOSS review: outdated links in "about" modal

### ISSUE THREAD

**Issue by Luthaf** [ToyotaResearchInstitute/materialnet#161]
Hi, I am one of the reviewer for the JOSS paper for materialnet. I'll open a few issues as I find surprising things while playing with material net.

On the live demo (https://toyotaresearchinstitute.github.io/materialnet), in the "about" modal, links points to an outdated URL for this repository: https://github.com/arclamp/materialnet/. Github redirect this to https://github.com/ToyotaResearchInstitute/materialnet/, so I guess the repository has been transferred at some point without updating the URLS.

**Comment by Luthaf** [comment]
Somehow related, the package.json homepage is set to https://toyotaresearchinstitute.github.io/materialnet, but the JOSS paper refers to https://maps.matr.io. Is any of these the main URL for a live demo/homepage?

If so, the corresponding URL could be added in the readme or the github respository description.

**Comment by waxlamp** [comment]
@Luthaf, thank you for bringing these issues up. I have put in a fix for this issue, but it won't be visible on maps.matr.io until Monday, when our devops team has a chance to deploy it.

At that time, if you feel this issue has not been solved, please re-open it.
