### ISSUE TITLE
JOSS Review: Example usage

### ISSUE THREAD

**Issue by rcannood** [ToyotaResearchInstitute/materialnet#166]
Please provide example usage in the documentation (README.md) on how to use MaterialNet (openjournals/joss-reviews#2105). For example, could you write a small markdown on how to perform a relevant analysis in this software? What information do you wish to obtain from MaterialNet?

**Comment by rcannood** [comment]
Also, in the README.md it is not mentioned that the user should use `yarn start` to start the application.

**Comment by waxlamp** [comment]
I am consulting with my co-authors and will add this information as soon as we have it.

**Comment by Luthaf** [comment]
The example usage should also contains a description on how one could go from a database of materials to a full visualization: how to create the network, how to save it (which format(s) are accepted by MaterialNet), and how to load it in MaterialNet.

**Comment by waxlamp** [comment]
Please see [this branch](https://github.com/ToyotaResearchInstitute/materialnet/tree/example-usage) for an updated README that addresses these issues, and let me know what you think!

**Comment by rcannood** [comment]
Looks good to me! 

@Luthaf ?

**Comment by Luthaf** [comment]
Look good to me too 👍

**Comment by rcannood** [comment]
Alright, good job!
