### ISSUE TITLE
JOSS Review: Local installation hangs

### ISSUE THREAD

**Issue by rcannood** [ToyotaResearchInstitute/materialnet#167]
Related to the JOSS Review (openjournals/joss-reviews#2105). When I want to run the application locally, the application gets stuck loading a network. 

![Screenshot from 2020-02-26 11-44-36](https://user-images.githubusercontent.com/553642/75337544-7b456580-588d-11ea-8bce-77e97d58e1b2.png)

These are the commands I entered in order to run the application:
```bash
git clone https://github.com/ToyotaResearchInstitute/materialnet.git
cd materialnet
yarn install
yarn start
```

Any ideas on how I can get this to work?

**Comment by waxlamp** [comment]
Sorry about this. I will update the instructions and provide a data bundle suitable for local builds. I will report back here (via a pull request) when it's ready.

**Comment by waxlamp** [comment]
@rcannood, please try the build one more time using this branch: https://github.com/ToyotaResearchInstitute/materialnet/tree/data-bundle.

The README on that branch contains updated build instructions, and a pointer to a data bundle you can use to resolve this issue. If you run into trouble, please let me know and I will edit that branch until things are working.

**Comment by rcannood** [comment]
It works perfectly now, thanks!
