### ISSUE TITLE
JOSS Review: Provide community guidelines

### ISSUE THREAD

**Issue by rcannood** [ToyotaResearchInstitute/materialnet#169]
Please provide community guidelines for potential contributors (openjournals/joss-reviews#2105).

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by waxlamp** [comment]
@rcannood, please re-open this issue if you feel the CONTRIBUTING.md file is not sufficient.
